In [1]:
import torch

# Create tensors
tensor1 = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)
tensor2 = torch.ones((2,3))

print("Tensor 1:\n", tensor1)
print("Tensor 2:\n", tensor2)

# Basic operations
print("Sum of tensor1:", torch.sum(tensor1))
print("Mean of tensor1:", torch.mean(tensor1))
print("Element-wise multiplication:\n", tensor1 * 2)


Tensor 1:
 tensor([[1., 2., 3.],
        [4., 5., 6.]])
Tensor 2:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
Sum of tensor1: tensor(21.)
Mean of tensor1: tensor(3.5000)
Element-wise multiplication:
 tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])


In [ ]:
#Creating a 3x3 tensor and apply addition, multiplication, and division operations.

import torch
tensor1= torch.tensor([])